package jagex2.io;

public final class BZip2$BZip2State {
   public static int[] tt;
   public int anInt21;
   public int nInUse;
   public byte state_out_ch;
   public int bsLive;
   private final int BZ_MAX_ALPHA_SIZE = 258;
   public int state_out_len;
   public int c_nblock_used;
   public byte[] stream;
   public int bsBuff;
   private final int BZ_MAX_CODE_LEN = 23;
   public boolean[] inUse = new boolean[256];
   public int k0;
   public int next_in;
   private final int anInt5 = 1;
   public int tPos;
   public byte[] decompressed;
   public byte[] aByteArray3 = new byte[256];
   private final int BZ_G_SIZE = 50;
   public int next_out;
   public int avail_out;
   private final int anInt8 = 4;
   public int save_nblock;
   private final int BZ_MAX_SELECTORS = 18002;
   public int[] unzftab = new int[256];
   public int total_out_lo32;
   public int avail_in;
   public int[] anIntArray2 = new int[257];
   private int[] anIntArray3 = new int[257];
   public int total_in_lo32;
   public int currBlockNo;
   public boolean[] inUse16 = new boolean[16];
   public int total_out_hi32;
   public byte[] mtfa = new byte[4096];
   public int total_in_hi32;
   public int[] mtfbase = new int[16];
   public byte[] selector = new byte[18002];
   public byte[] selectorMtf = new byte[18002];
   public byte[][] len = new byte[6][258];
   public int[][] limit = new int[6][258];
   public boolean blockRandomized;
   public int[][] base = new int[6][258];
   public int[][] perm = new int[6][258];
   public int origPtr;
   public int[] minLens = new int[6];
}
